version: '2'

services:

  quotes-service:
    image: magnuslarsson/quotes:16
#    environment:
#      - SPRING_CLOUD_DISCOVERY_ENABLED=false

#    ports:
#      - "9090:9090"

#  portal.js:
#    image: magnuslarsson/portal.js:1
#    ports:
#      - "7070:80"

  portal-service:
    image: magnuslarsson/portal:17
    ports:
      - "9090:9090"
#    environment:
#      - SPRING_CLOUD_DISCOVERY_ENABLED=false
